Repository Daywalkerchen/awesome-extension, pull requests merged in 2022-12, with the labels that each got.

#1 :sparkles: :blobdance: Add emotes to anchors
  src/pages/Content/modules/emotes/replaceEmotes.js
Labels: enhancement

#3 v1.0.1
  README.md
  package.json
  src/const/emotes.js
Labels: enhancement

#4 Added :couldyounot:
  src/const/emotes.js
Labels: new emote

#5 v1.0.2
  README.md
  doc/developing.md
  doc/manifest.md
  package.json
  src/manifest.json
  src/pages/Content/index.js
  src/pages/Content/modules/emotes/replaceEmotes.js
Labels: documentation, enhancement

#6 :sparkles: :bug: Add span support and fix wierd node stuff in rocket
  src/pages/Content/modules/emotes/replaceEmotes.js
Labels: bug, enhancement

#7 Options in Popouts, Alternate names for emotes, minor performance improvement.
  README.md
  doc/img/popout.png
  package-lock.json
  src/const/emotes.js
  src/pages/Content/modules/emotes/replaceEmotes.js
  src/pages/Content/modules/storage/storage.js
  src/pages/Popup/index.html
  src/pages/Popup/popup.js
  utils/test-page.html
Labels: documentation, enhancement

#10 :art: Update prettier config and execute
  .prettierrc
  doc/developing.md
  doc/manifest.md
  src/const/emotes.js
  src/manifest.json
  src/pages/Background/index.js
  src/pages/Content/modules/emotes/emote.scss
  src/pages/Content/modules/emotes/replaceEmotes.js
  src/pages/Devtools/index.js
  src/pages/Options/index.jsx
  src/pages/Panel/Panel.css
  src/pages/Popup/Popup.jsx
  src/pages/Popup/Popup.scss
  src/pages/Popup/index.css
  src/pages/Popup/index.jsx
  utils/build.js
  utils/webserver.js
  webpack.config.js
Labels: enhancement

#12 :memo: Update documentation
  README.md
  doc/emotes.md
  doc/img/popout.png
  package-lock.json
Labels: documentation

#11 :recycle: Use querySelectorAll instead of multiple other calls
  src/pages/Content/modules/emotes/replaceEmotes.js
Labels: enhancement

#16 🧑‍💻 🔨 Preeeecommit hook :hype:
  .husky/.gitignore
  .husky/pre-commit
  README.md
  package-lock.json
  package.json
Labels: documentation, enhancement

#19 :sparkles: Add some new emotes
  src/const/emotes.js
Labels: new emote

#21 added :kappa:
  src/const/emotes.js
Labels: new emote

#25 :bug: Prevent reloading errors
  src/pages/Content/index.js
  src/pages/Content/modules/emotes/emoteInserter.js
  src/pages/Popup/emote-picker/EmotePicker.jsx
  src/pages/Popup/emote-picker/emote/Emote.jsx
  src/pages/Popup/emote-picker/emote/emote.scss
  src/pages/Popup/emote-picker/emotePicker.scss
Labels: bug

#30 ✨ add :derp:-emote and :vibe: alias for :vibebunny:
  src/assets/img/emotes/derp.png
  src/const/emotes.js
Labels: new emote

#29 ✏️ 🚸 Shorten counter by using k,M,B notation; Color coded counter based on common RPG iItem quality color (skipped green tho, cause it looked ugly)
  src/const/messages.js
  src/pages/Background/badge.js
  src/pages/Background/contextMenu.js
  src/pages/Background/index.js
  src/pages/Content/index.js
Labels: enhancement

#33 Replaced text with image for emoji picker
  src/pages/Popup/emote-picker/emote/Emote.jsx
Labels: enhancement

#36 :sparkles: Add :bulbasaur:
  src/assets/emotes/bulbasaur.gif
  src/const/emotes.js
Labels: new emote

#37 🚸 Seeded daily schedule w/ day string so that all users will create the same schedule
  package-lock.json
  package.json
  src/pages/Content/modules/better-big-blue-button/betterBigBlueButton.js
Labels: enhancement
