Repository Daywalkerchen/awesome-extension, pull requests merged in 2023-01, with the labels that each got.

#57 :bug: Remove "webcam" from appearing as a username in BBBB schedule
  src/features/Content/modules/better-big-blue-button/betterBigBlueButton.js
Labels: bug

#61 Fix BBBB Webcam bug
  src/features/Content/modules/better-big-blue-button/betterBigBlueButton.js
Labels: bug

#62 ✨ added blobsaber
  src/assets/emotes/blobsaber.gif
  src/const/emotes.js
Labels: new emote

#49 :sparkles: Add searchbar to emote picker
  src/components/emote-picker-on-input/EmotePickerOnInput.jsx
  src/components/emote-picker/EmotePicker.jsx
  src/components/search-bar/SearchBar.jsx
  src/components/search-bar/searchBar.scss
  src/features/Popup/Popup.jsx
Labels: enhancement

#69 :bug: Fix EmotePicker being selectable and run prettier
  src/components/emote-picker-on-input/EmotePickerOnInput.jsx
  src/components/emote-picker/EmotePicker.jsx
  src/features/Background/badge.js
  src/features/Background/contextMenu.js
  src/features/Content/content.styles.css
  src/features/Content/modules/better-big-blue-button/betterBigBlueButton.js
  src/features/Content/modules/emote-picker-on-chat-boxes/emotePickerOnChatBoxes.js
  src/features/Content/modules/emote-picker-on-chat-boxes/emotePickerOnChatBoxes.scss
  src/manifest.json
Labels: bug

#75 :poop: Add emotePicker in BBB with very cursed code / design
  src/features/Content/index.js
  src/features/Content/modules/emote-picker-on-chat-boxes/emotePickerOnChatBoxes.js
  src/features/Content/modules/emote-picker-on-chat-boxes/emotePickerOnChatBoxes.scss
Labels: enhancement

#76 :bento: Add 28px icon for emotepickeroninput
  src/assets/img/icon-28.png
  src/components/emote-picker-on-input/EmotePickerOnInput.jsx
  src/features/Content/modules/emote-picker-on-chat-boxes/emotePickerOnChatBoxes.scss
  src/manifest.json
Labels: enhancement
